# Copyright 2021 Canonical
# See LICENSE file for licensing details.

options:

  ### Application-related options:
  server-deployment-mode:
    type: string
    # TODO(aznashwan): check what other possible modes there are and
    # offer a more detailed description on them.
    default: TEST_IGNORE_FUNCTION_MATCH
    description: Server deployment mode.
  
  server-logging-level:
    type: string
    default: INFO
    description: |
      String identifier of the log level to be used for all library classes.
      Must be one of INFO, WARN, DEBUG, or TRACE, or OFF.

  server-pac4j-logging-level:
    type: string
    default: DEBUG
    description: |
      String identifier of the log level to be used by authentication-related
      PAC4J actions. Must be one of INFO, WARN, DEBUG, or TRACE, or OFF.

  ### Nginx Ingress Integrator-related options:
  enable-tls:
    type: boolean
    default: false
    description: |
      Boolean representing whether or not this Legend Application endpoint is
      accessed through HTTPS. Setting this option will not enable TLS on the
      service itself, and it is meant to be used in conjunction with the
      tls-secret-name config option on the Nginx Ingress Integrator Charm.
      Setting this option will cause the Gitlab Callback URLs to be prefixed
      by HTTPS instead of HTTP, and update Studio to use the HTTPS Service URL.

  external-hostname:
    type: string
    default: ""
    description: |
      String representing the DNS name this Application should respond to.
      By default, this will be the Application's name.

  # TODO(aznashwan): ask whether 'opentracing' options are worth exposing.
  # https://github.com/finos/legend/blob/master/installers/docker-compose/shared/templates/engine/config.json#L45
